"""Add date_favorited to favorite_dish

Revision ID: 455c538d80dd
Revises: ca468b12b88b
Create Date: 2024-09-21 02:19:42.849554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '455c538d80dd'
down_revision = 'ca468b12b88b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_dish', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_favorited', sa.DateTime(), nullable=True))
        batch_op.alter_column('dish_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_dish', schema=None) as batch_op:
        batch_op.alter_column('dish_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('date_favorited')

    # ### end Alembic commands ###
